### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by eggplants** [cordx56/moudame.com#1]
GitHub Pagesでは設定した独自ドメインに対してSSL証明書を発行できます。

Ref: <https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain>

**Comment by cordx56** [comment]
こんにちは。 @eggplants さん。
こちらからは既に Let's Encrypt で正常にSSL証明書が発行されているように見えていますが、そちらからは正常に証明書が見られていないということでしょうか。

**Comment by eggplants** [comment]
`https://moudame.com`でアクセスするとSSL化されていました。お手数おかけしました…

![image](https://user-images.githubusercontent.com/42153744/145955793-1d9c43ba-73af-41e6-810a-1f20b6a882ed.png)
